const products = [
  {
    _id: '20',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 40000,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '21',
    name: 'iPhone 11 Pro Max 256GB Memory ',
    image: '/images/phone.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 170000,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '22',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 120000,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '23',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 130000,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '24',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 20000,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '25',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 15000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '1',
    name: 'Celular Libre Samsung A52 Negro',
    image: '/images/GalaxyA52.png',
    description:
      'Celular Samsung modelo A52 cuenta con un procesador SDM720G octa/core 2.3Ghz una memoria RAM de 6GB y 128GB de almacenamiento interno expandible hasta 1TB con una tarjeta microSD, sonido potente con dolby atmos *2 parlantes integrados(, desbloqueo con huella dactilar en pantalla *FOD( NFC, one UI3.1,protección IP67 *resistente hasta 1M de profundidad en agua dulce durante 30 minutos(, batería de 4.500mAh para mayor duración de la batería y 25W super fast charging, pantalla infinity/0 display de 6.5@ FHD supera moled *90Hz(, cámara frontal de 32MP y cuádruple cámara trasera de 64MP',
    brand: 'Samsung',
    category: 'SmartPhone',
    price: 91499,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Celular Libre Samsung A32 Blanco',
    image: '/images/GalaxyA32.png',
    description:
      'Celular libre sansung modelo A32 cuenta con una camara proncipal de 64+8+5+5MP una camara frontal de 20MP y flach, memoria interna de 128GB expandibla a 1TB en una micro SD, memoria RAM de 4GB, pantalla de 6.4" super AMOLED la resolucion de la pantalla es de 1080x2400 FH+,funcion NFC,bluetooth,WI-FI el sistema operativo es android 11, octa-core2GHz,1.8GHz, parlante exterio y bateria de 5000mAh.',
    brand: 'Samsung',
    category: 'SmartPhone',
    price: 75999,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Celular Libre Motorola G60s Azul',
    image: '/images/Motog60s.png',
    description:
      'Celular Motorola G60s cuenta con una pantalla de 6.78@ * 1080x2460, 396ppi,HiD,120Hz(, sistema operativo android 11, procesador octa core 1.8Ghz * mediatek helio G95(, 4 cámara trasera 64]08]05]02MP, flash led, cámara frontal de 16MP con flash frontal, 6GB de memoria RAM y 128GB de memoria interna *disponible para el usuario 110GB( , expandible a 1TB con una tarjeta micro SD, acelerómetro, sensor de proximidad, brújula, huella dactilar, desbloqueofacial, wi fi y bluetooth, nano sim , batería de 5000 mAh con cargador turbo, con radio FM, no trae auriculares.',
    brand: 'Motorola',
    category: 'SmartPhone',
    price: 62999,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Celular Libre Samsung S22 Ultra Blanco',
    image: '/images/S22Ultra.png',
    description:
      'Con el nuevo modelo de Samsung es el primer S Pen incorporado en el Galaxy S tiene una clasificación IP68 y pone la precisión al alcance de tu mano trae una pantalla quad HD+ edge de 6.8" con lector de huellas dactilares ultrasónico y reconocimiento facial, viene con marco de aluminio, la batería es de 5000 mAh y carga superrápida de 25 watts, el procesador es un octa-core, la memoria RAM es de 12GB y su memoria interna es de 256GB, dual SIM.',
    brand: 'Samsung',
    category: 'SmartPhone',
    price: 299999,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Celular Libre Samsung A03 Negro',
    image: '/images/SamsungA03.png',
    description:
      'Celular Samsung A03 cuenta con un procesador octa-core 1.6GHz, la pantalla es de 6.5" HD+ la cámara frontal es de 5.0mpx y la cámara trasera es de 48+02mpx, la memoria RAM es de 4GB y 128GB de memoria expandible a 1TB con una tarjeta micro SD, buetooth 5.0 y la batería es de 5000 mAh.',
    brand: 'Samsung',
    category: 'SmartPhone',
    price: 47999,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Celular Libre Motorola G52 Negro',
    image: '/images/MotoG52.png',
    description:
      'Hacé que tu entretenimiento favorito cobre vida con el contraste infinito que ofrece tonos oscuros más profundos y colores más brillantes, en la pantalla FHD+ de 6.6" y 90 Hz con tecnología pOLED. Gracias a la resolución Full HD+.',
    brand: 'Motorola',
    category: 'SmartPhone',
    price: 62999,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Celular Libre Samsung A22 5G',
    image: '/images/GalaxyA22.png',
    description:
      'Celular Samsung A22 5G cuenta con un procesador octa-core 2.2GHz, la pantalla es de 6.6", la cámara frontal es de 8.0mpx y la cámara trasera es de 48+05+02mpx, la memoria RAM es de 4GB y 128GB de memoria expandible a 1TB con una tarjeta micro SD, buetooth 5.0.',
    brand: 'Samsung',
    category: 'SmartPhone',
    price: 69999,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Smart Philips 65" 4K Android tv',
    image: '/images/SmartPhilips65-4k.jpg',
    description:
      'El nuevo Smart Philips cuenta con una resolución 4K UHD, con tecnología Ambilight en 3 lados y el sistema operativo Android tv Cuenta con control por voz con el Asistente de Google, HDR para imágenes brillantes, el diseño atractivo y ultra fino con marco plateado, Dolby Visión y Dolby Atmos para visión y sonido cinematográfico.',
    brand: 'Philips',
    category: 'Televisores',
    price: 179999,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Aire Split Philco f/c 3350Watts',
    image: '/images/AireSplitPhilco3350watts.jpg',
    description:
      'Eficiencia energética clase A. Refrigerante ecológico R410a. Display oculto. Control remoto multifunción. Barrido de aire automático. Súper silencioso. Función sleep. Timer programable. Filtros lavables.',
    brand: 'Philco',
    category: 'Climatización',
    price: 112099,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Lavarropas Automático Drean Next 8.14P Eco Inverter',
    image: '/images/LavarropasAutomaticoDreanNext.jpg',
    description:
      'Lavarropas Drean next 8.14P eco inverter, clase A]]], 1400 RPM en el centrifugado, 8 kg de ropa, display led color * te indica el tiempo real el programa seleccionado , la temperatura asociada, la velocidad del centrifugado, el avance del ciclo en cada etapa de lavado y el tiempo remanente(, luz interior de tambor, bisagra 180grados, cúpula de vidrio, silencioso y económico ahorra hasta un 30% de energía comparado con un lavarropas clase A .',
    brand: 'Drean',
    category: 'Lavado/Secado',
    price: 98129,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Cama Superpuesta Var Ideas Gris',
    image: '/images/camacucheta.png',
    description:
      'CAMA SUPERPUESTA VAR IDEAS GRIS. Cama de 1 plaza. Hecha en aluminio de máxima durabilidad. Rápida para armar. Desmontable. Color Gris.',
    brand: 'Cannon',
    category: 'Camas',
    price: 39099,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Sofá Color Living Dubais 3 Cuerpos Negro',
    image: '/images/sofacolorliving.PNG',
    description:
      'Sofá Color Living modelo Dubais cuenta con una estructura de madera maciza, libre de nudos, el asiento esta conformado por una estructura de resortes el relleno es de resortes recubiertos por placas de poliester y el apoyo esta sobre patas de madera maciza lustrada.',
    brand: 'Dubais',
    category: 'Muebles',
    price: 133069,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Rack LÍnea Brasil New Blumeneau para 70"',
    image: '/images/RackLineaBrasil.PNG',
    description:
      'Rack Línea Brasil modelo New Blumenau para Led de 70" cuenta con dos puertas corredizas y estantes con salida para cables.',
    brand: 'New Blumeneau',
    category: 'Muebles',
    price: 35649,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Ropero Delos Ecoplus 4 Puertas Mogno',
    image: '/images/RoperoDelosEcoplus.PNG',
    description:
      'Ropero Delos modelo Ecoplus cuenta con cuatro puertas de abrir, dos cajones con guias metálicas y el interior es revestido.',
    brand: 'Mogno',
    category: 'Muebles',
    price: 32819,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '15',
    name: 'Juego de Comedor Kappesberg Munique Mesa+6 Sillas',
    image: '/images/juegodecomedorkappesberg.PNG',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Kappesberg',
    category: 'Muebles',
    price: 124879,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '16',
    name: 'Termometro Digital Telefunken',
    image: '/images/TermometroDigitalTelefunken.png',
    description:
      'Termómetro digital Telefunken cuenta con u visor led, bajo consumo energético, selector de unidad ( C o F ), el rango de temperatura es de -50 a 200 grados centígrados, alta estabilidad, apagado automático.',
    brand: 'Telefunken',
    category: 'Artículo de cocina',
    price: 2869,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '17',
    name: 'Picadora Moulinex Fresh Expres 150Watts',
    image: '/images/PicadoraMoulinex.png',
    description:
      'Se trata de un rallador y cortador de verduras, frutas, chocolate, queso, frutas secas. Cuenta con óptimos 150 WATTS DE POTENCIA. Ofrece 5 CONOS, especiales para rallado fino, rallado grueso, corte fino, corte ondulado y queso rallado. Se destaca la comodidad de su FÁCIL SALIDA DEL ALIMENTO, directo al plato, que ahorra tiempo y aporta significativamente en limpieza',
    brand: 'Maulinex',
    category: 'Artículo de cocina',
    price: 14109,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '18',
    name: 'Cortadora De Alimentos Ultracomb',
    image: '/images/CortadoraDeAlimentos.png',
    description:
      'Motor de 150W. Cuchilla en acero inoxidable de 190 mm de diámetro, desmontable para una fácil limpieza. Tracción de cuchilla por engranaje. Espesor de corte ajustable entre 0-15 mm. Bandeja para soporte y arrastre de alimentos en alumminio.',
    brand: 'Ultracomb',
    category: 'Artículo de cocina',
    price: 24289,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '19',
    name: 'Sandwichera Atma 1000Watts',
    image: '/images/SandwicheraAtma.png',
    description:
      'Sorprende a tu familia con las más exquisitas combinaciones de tostados, la sandwichera ATMA SM-8911E posee capacidad para 2 sándwiches, superficie antiadherente, placas cuadradas, indicador luminoso. Almacenamiento vertical para facilitar su guardado.',
    brand: 'Atma',
    category: 'Artículo de cocina',
    price: 8239,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
]

export default products
